// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_battery_android_frame_5_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_5_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_lorawan_logo_white_png);    // assets/LoRaWAN_Logo_white.png
LV_IMG_DECLARE(ui_img_mqtt_logo_png);    // assets/mqtt_logo.png
LV_IMG_DECLARE(
    ui_img_satellite_alt_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/satellite_alt_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_1015935_png);    // assets/1015935.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_alert_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_alert_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_lock_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_lock_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_off_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_off_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_plus_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_plus_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_android_wifi_3_bar_question_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/android_wifi_3_bar_question_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_1_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_1_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_2_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_2_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_3_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_3_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_4_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_4_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_6_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_6_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_alert_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_alert_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_bolt_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_bolt_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_full_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_full_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_plus_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_plus_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_battery_android_frame_question_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_frame_question_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_wifi_1_bar_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/wifi_1_bar_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_wifi_2_bar_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/wifi_2_bar_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
