// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_batContainer = NULL;
lv_obj_t * ui_batImg = NULL;
lv_obj_t * ui_batVal = NULL;
lv_obj_t * ui_loraContainer = NULL;
lv_obj_t * ui_loraImg = NULL;
lv_obj_t * ui_mqttContainer = NULL;
lv_obj_t * ui_mqttImg = NULL;
lv_obj_t * ui_gpsContainer = NULL;
lv_obj_t * ui_gpsImg = NULL;
lv_obj_t * ui_gpsSat = NULL;
lv_obj_t * ui_wifiContainer = NULL;
lv_obj_t * ui_wifiImg = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_WifiAPText = NULL;
lv_obj_t * ui_WifiSTAText = NULL;
lv_obj_t * ui_mainData = NULL;
lv_obj_t * ui_leftMainData = NULL;
lv_obj_t * ui_co2Container = NULL;
lv_obj_t * ui_co2Value = NULL;
lv_obj_t * ui_co2Units = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_tempContainer = NULL;
lv_obj_t * ui_tempValue = NULL;
lv_obj_t * ui_tempUnits = NULL;
lv_obj_t * ui_humContainer = NULL;
lv_obj_t * ui_humValue = NULL;
lv_obj_t * ui_humUnits = NULL;
lv_obj_t * ui_rightMainData = NULL;
lv_obj_t * ui_speedContainer = NULL;
lv_obj_t * ui_speedValue = NULL;
lv_obj_t * ui_speedUnits = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_altitudeContainer = NULL;
lv_obj_t * ui_altitudeValue = NULL;
lv_obj_t * ui_altitudeUnits = NULL;
lv_obj_t * ui_courseContainer = NULL;
lv_obj_t * ui_courseValue = NULL;
lv_obj_t * ui_courseUnits = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0E0C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_height(ui_header, 40);
    lv_obj_set_width(ui_header, lv_pct(100));
    lv_obj_set_align(ui_header, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_header, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x383E65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_batContainer);
    lv_obj_set_width(ui_batContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_batContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_batContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_batContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_batContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_batContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_batContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_batContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_batContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_batContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batImg = lv_image_create(ui_batContainer);
    lv_image_set_src(ui_batImg, &ui_img_battery_android_frame_5_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_batImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batVal = lv_label_create(ui_batContainer);
    lv_obj_set_width(ui_batVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batVal, "4,18v");

    ui_loraContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_loraContainer);
    lv_obj_set_height(ui_loraContainer, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_flex_grow(ui_loraContainer, 1);
    lv_obj_set_align(ui_loraContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_loraContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_loraContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_loraContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_loraContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_loraContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_loraContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_loraContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loraImg = lv_image_create(ui_loraContainer);
    lv_image_set_src(ui_loraImg, &ui_img_lorawan_logo_white_png);
    lv_obj_set_width(ui_loraImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loraImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loraImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loraImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_loraImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mqttContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_mqttContainer);
    lv_obj_set_height(ui_mqttContainer, 50);
    lv_obj_set_flex_grow(ui_mqttContainer, 1);
    lv_obj_set_align(ui_mqttContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mqttContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_mqttContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mqttContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mqttContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mqttContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqttImg = lv_image_create(ui_mqttContainer);
    lv_image_set_src(ui_mqttImg, &ui_img_mqtt_logo_png);
    lv_obj_set_width(ui_mqttImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mqttImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mqttImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mqttImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_mqttImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpsContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_gpsContainer);
    lv_obj_set_width(ui_gpsContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpsContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpsContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpsContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpsContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_gpsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_gpsContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_gpsContainer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_gpsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_gpsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_gpsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_gpsContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpsImg = lv_image_create(ui_gpsContainer);
    lv_image_set_src(ui_gpsImg, &ui_img_satellite_alt_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_gpsImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpsImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpsImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gpsImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_gpsImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpsSat = lv_label_create(ui_gpsContainer);
    lv_obj_set_width(ui_gpsSat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpsSat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpsSat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpsSat, "-");

    ui_wifiContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_wifiContainer);
    lv_obj_set_width(ui_wifiContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifiContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_wifiContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifiContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifiContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifiContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_wifiContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_wifiContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiImg = lv_image_create(ui_wifiContainer);
    lv_image_set_src(ui_wifiImg, &ui_img_android_wifi_3_bar_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_wifiImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_wifiContainer);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiAPText = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_WifiAPText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiAPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiAPText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiAPText, "AP");
    lv_obj_set_style_text_color(ui_WifiAPText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiAPText, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSTAText = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_WifiSTAText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSTAText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSTAText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiSTAText, "STA");
    lv_obj_set_style_text_color(ui_WifiSTAText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiSTAText, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainData = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_mainData);
    lv_obj_set_height(ui_mainData, 140);
    lv_obj_set_width(ui_mainData, lv_pct(100));
    lv_obj_set_align(ui_mainData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mainData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mainData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_mainData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_mainData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftMainData = lv_obj_create(ui_mainData);
    lv_obj_remove_style_all(ui_leftMainData);
    lv_obj_set_width(ui_leftMainData, lv_pct(50));
    lv_obj_set_height(ui_leftMainData, lv_pct(100));
    lv_obj_set_align(ui_leftMainData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leftMainData, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_leftMainData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_leftMainData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftMainData, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftMainData, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftMainData, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_leftMainData, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_leftMainData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_leftMainData, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2Container = lv_obj_create(ui_leftMainData);
    lv_obj_remove_style_all(ui_co2Container);
    lv_obj_set_height(ui_co2Container, lv_pct(60));
    lv_obj_set_width(ui_co2Container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_co2Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_co2Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_co2Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_co2Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_co2Value = lv_label_create(ui_co2Container);
    lv_obj_set_width(ui_co2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_co2Value, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_co2Value, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_co2Value, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_co2Value, "662");
    lv_obj_remove_flag(ui_co2Value, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_co2Value, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_co2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_co2Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_co2Value, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_co2Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2Units = lv_label_create(ui_co2Container);
    lv_obj_set_width(ui_co2Units, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2Units, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_co2Units, 7);
    lv_obj_set_y(ui_co2Units, 8);
    lv_obj_set_align(ui_co2Units, LV_ALIGN_CENTER);
    lv_label_set_text(ui_co2Units, "ppm");
    lv_obj_set_style_text_color(ui_co2Units, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_co2Units, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_leftMainData);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(90));
    lv_obj_set_flex_grow(ui_Container3, 1);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempContainer = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_tempContainer);
    lv_obj_set_height(ui_tempContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_tempContainer, 1);
    lv_obj_set_align(ui_tempContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tempContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempValue = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_tempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempValue, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_tempValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_tempValue, "21.4");
    lv_obj_remove_flag(ui_tempValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_tempValue, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempUnits = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_tempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempUnits, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_tempUnits, "°C");
    lv_obj_set_style_text_color(ui_tempUnits, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humContainer = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_humContainer);
    lv_obj_set_height(ui_humContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_humContainer, 1);
    lv_obj_set_align(ui_humContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_humContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_humContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humValue = lv_label_create(ui_humContainer);
    lv_obj_set_width(ui_humValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_humValue, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_humValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_humValue, "34.6");
    lv_obj_remove_flag(ui_humValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humValue, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_humValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humUnits = lv_label_create(ui_humContainer);
    lv_obj_set_width(ui_humUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humUnits, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_humUnits, "%rH");
    lv_obj_set_style_text_color(ui_humUnits, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightMainData = lv_obj_create(ui_mainData);
    lv_obj_remove_style_all(ui_rightMainData);
    lv_obj_set_width(ui_rightMainData, lv_pct(50));
    lv_obj_set_height(ui_rightMainData, lv_pct(100));
    lv_obj_set_align(ui_rightMainData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rightMainData, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rightMainData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rightMainData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightMainData, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightMainData, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightMainData, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rightMainData, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rightMainData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rightMainData, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedContainer = lv_obj_create(ui_rightMainData);
    lv_obj_remove_style_all(ui_speedContainer);
    lv_obj_set_height(ui_speedContainer, lv_pct(60));
    lv_obj_set_width(ui_speedContainer, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_speedContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_speedContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_speedContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_speedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedValue = lv_label_create(ui_speedContainer);
    lv_obj_set_width(ui_speedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_speedValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_speedValue, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_speedValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_speedValue, "12.5");
    lv_obj_remove_flag(ui_speedValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_speedValue, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speedValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_speedValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedUnits = lv_label_create(ui_speedContainer);
    lv_obj_set_width(ui_speedUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedUnits, 7);
    lv_obj_set_y(ui_speedUnits, 8);
    lv_obj_set_align(ui_speedUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedUnits, "km/h");
    lv_obj_set_style_text_color(ui_speedUnits, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_rightMainData);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(90));
    lv_obj_set_flex_grow(ui_Container2, 1);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_altitudeContainer = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_altitudeContainer);
    lv_obj_set_height(ui_altitudeContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_altitudeContainer, 1);
    lv_obj_set_align(ui_altitudeContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_altitudeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_altitudeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_altitudeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_altitudeValue = lv_label_create(ui_altitudeContainer);
    lv_obj_set_width(ui_altitudeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_altitudeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_altitudeValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_altitudeValue, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_altitudeValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_altitudeValue, "113");
    lv_obj_remove_flag(ui_altitudeValue,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_altitudeValue, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_altitudeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_altitudeValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_altitudeValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_altitudeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_altitudeUnits = lv_label_create(ui_altitudeContainer);
    lv_obj_set_width(ui_altitudeUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_altitudeUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_altitudeUnits, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_altitudeUnits, "m");
    lv_obj_set_style_text_color(ui_altitudeUnits, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_altitudeUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_courseContainer = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_courseContainer);
    lv_obj_set_height(ui_courseContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_courseContainer, 1);
    lv_obj_set_align(ui_courseContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_courseContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_courseContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_courseContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_courseValue = lv_label_create(ui_courseContainer);
    lv_obj_set_width(ui_courseValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_courseValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_courseValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_courseValue, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_courseValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_courseValue, "189");
    lv_obj_remove_flag(ui_courseValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_courseValue, lv_color_hex(0x73FFFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_courseValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_courseValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_courseValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_courseValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_courseUnits = lv_label_create(ui_courseContainer);
    lv_obj_set_width(ui_courseUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_courseUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_courseUnits, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_courseUnits, "°");
    lv_obj_set_style_text_color(ui_courseUnits, lv_color_hex(0x6287F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_courseUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_header = NULL;
    ui_batContainer = NULL;
    ui_batImg = NULL;
    ui_batVal = NULL;
    ui_loraContainer = NULL;
    ui_loraImg = NULL;
    ui_mqttContainer = NULL;
    ui_mqttImg = NULL;
    ui_gpsContainer = NULL;
    ui_gpsImg = NULL;
    ui_gpsSat = NULL;
    ui_wifiContainer = NULL;
    ui_wifiImg = NULL;
    ui_Container1 = NULL;
    ui_WifiAPText = NULL;
    ui_WifiSTAText = NULL;
    ui_mainData = NULL;
    ui_leftMainData = NULL;
    ui_co2Container = NULL;
    ui_co2Value = NULL;
    ui_co2Units = NULL;
    ui_Container3 = NULL;
    ui_tempContainer = NULL;
    ui_tempValue = NULL;
    ui_tempUnits = NULL;
    ui_humContainer = NULL;
    ui_humValue = NULL;
    ui_humUnits = NULL;
    ui_rightMainData = NULL;
    ui_speedContainer = NULL;
    ui_speedValue = NULL;
    ui_speedUnits = NULL;
    ui_Container2 = NULL;
    ui_altitudeContainer = NULL;
    ui_altitudeValue = NULL;
    ui_altitudeUnits = NULL;
    ui_courseContainer = NULL;
    ui_courseValue = NULL;
    ui_courseUnits = NULL;

}
