// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_batContainer;
extern lv_obj_t * ui_batImg;
extern lv_obj_t * ui_batVal;
extern lv_obj_t * ui_loraContainer;
extern lv_obj_t * ui_loraImg;
extern lv_obj_t * ui_mqttContainer;
extern lv_obj_t * ui_mqttImg;
extern lv_obj_t * ui_gpsContainer;
extern lv_obj_t * ui_gpsImg;
extern lv_obj_t * ui_gpsSat;
extern lv_obj_t * ui_wifiContainer;
extern lv_obj_t * ui_wifiImg;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_WifiAPText;
extern lv_obj_t * ui_WifiSTAText;
extern lv_obj_t * ui_mainData;
extern lv_obj_t * ui_leftMainData;
extern lv_obj_t * ui_co2Container;
extern lv_obj_t * ui_co2Value;
extern lv_obj_t * ui_co2Units;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_tempContainer;
extern lv_obj_t * ui_tempValue;
extern lv_obj_t * ui_tempUnits;
extern lv_obj_t * ui_humContainer;
extern lv_obj_t * ui_humValue;
extern lv_obj_t * ui_humUnits;
extern lv_obj_t * ui_rightMainData;
extern lv_obj_t * ui_speedContainer;
extern lv_obj_t * ui_speedValue;
extern lv_obj_t * ui_speedUnits;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_altitudeContainer;
extern lv_obj_t * ui_altitudeValue;
extern lv_obj_t * ui_altitudeUnits;
extern lv_obj_t * ui_courseContainer;
extern lv_obj_t * ui_courseValue;
extern lv_obj_t * ui_courseUnits;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

