// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background[2] = {0x383E65, 0x383E65};
const ui_theme_variable_t _ui_theme_alpha_background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_backgroundLines[2] = {0x6287F8, 0x6287F8};
const ui_theme_variable_t _ui_theme_alpha_backgroundLines[2] = {220, 220};

const ui_theme_variable_t _ui_theme_color_values[2] = {0x73FFFE, 0x73FFFE};
const ui_theme_variable_t _ui_theme_alpha_values[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_lines1[2] = {0xFBF665, 0xFBF665};
const ui_theme_variable_t _ui_theme_alpha_lines1[2] = {220, 220};

const ui_theme_variable_t _ui_theme_color_lines2[2] = {0xFF6E21, 0xFF6E21};
const ui_theme_variable_t _ui_theme_alpha_lines2[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

