// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_BACKGROUNDLINES 1
#define UI_THEME_COLOR_VALUES 2
#define UI_THEME_COLOR_LINES1 3
#define UI_THEME_COLOR_LINES2 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_THEME1 1

extern const ui_theme_variable_t _ui_theme_color_background[2];
extern const ui_theme_variable_t _ui_theme_alpha_background[2];

extern const ui_theme_variable_t _ui_theme_color_backgroundLines[2];
extern const ui_theme_variable_t _ui_theme_alpha_backgroundLines[2];

extern const ui_theme_variable_t _ui_theme_color_values[2];
extern const ui_theme_variable_t _ui_theme_alpha_values[2];

extern const ui_theme_variable_t _ui_theme_color_lines1[2];
extern const ui_theme_variable_t _ui_theme_alpha_lines1[2];

extern const ui_theme_variable_t _ui_theme_color_lines2[2];
extern const ui_theme_variable_t _ui_theme_alpha_lines2[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
